### ISSUE TITLE
Zuul should report back to github on failure

### ISSUE THREAD

**Issue by jamielennox** [BonnyCI/projman#115] opened 2017-02-09 05:28 UTC
So I was doing some testing with zuul on a repo that had branch protection enabled. The branch protection criteria was not met, but because we were using labels at the time i could trigger a bonny approved. 

I'm pretty sure zuul tried to perform the merge and everything but github rejected the push because the branch protection failed. 

It'll be way to difficult to make zuul read and understand github's branch protection (at least for now) but at the very least when a merge or push failure happens zuul should drop a comment to say that something went wrong, what happened and what to do next.

**Comment by gandelman-a** [comment] 2017-02-13 23:54
I just hit this as well, in my case:

* Proposed PR
* PR  approved from human 
* travis failed
* bonny check passes
* passing check triggers the gate
* Zuul cant merge because the required travis check has failed

Resulted in the following trace on zuul. 

```
2017-02-13 23:52:13,622 ERROR zuul.DependentPipelineManager: Exception while reporting:
Traceback (most recent call last):
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/scheduler.py", line 1806, in _reportItem
    ret = self.sendReport(actions, self.pipeline.source, item)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/scheduler.py", line 1333, in sendReport
    ret = reporter.report(source, self.pipeline, item)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/reporter/github.py", line 60, in report
    self.mergePull(item)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/reporter/github.py", line 114, in mergePull
    self.connection.mergePull(owner, project, pr_number, message, sha)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/connection/github.py", line 535, in mergePull
    ' conflict, original error is %s' % e)
MergeFailure: Merge was not successful due to mergeability conflict, original error is 405 Required status check "continuous-integration/travis-ci/pr" is failing.
2017-02-13 23:52:13,622 ERROR zuul.DependentPipelineManager: Exception while reporting:
Traceback (most recent call last):
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/scheduler.py", line 1806, in _reportItem
    ret = self.sendReport(actions, self.pipeline.source, item)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/scheduler.py", line 1333, in sendReport
    ret = reporter.report(source, self.pipeline, item)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/reporter/github.py", line 60, in report
    self.mergePull(item)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/reporter/github.py", line 114, in mergePull
    self.connection.mergePull(owner, project, pr_number, message, sha)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/connection/github.py", line 535, in mergePull
    ' conflict, original error is %s' % e)
MergeFailure: Merge was not successful due to mergeability conflict, original error is 405 Required status check "continuous-integration/travis-ci/pr" is failing.
```

**Comment by gandelman-a** [comment] 2017-02-14 00:00
Also, after posting a new revision to the PR, jobs do not start. The following errors are in server.log:
```
2017-02-13 23:58:19,329 WARNING zuul.Scheduler: Build set <BuildSet item: <QueueItem 0x7f17f81c5310 for 142,396c6c21df72837189484f8232fda58588029b06 in gate_github> #builds: 0 merge state: PENDING> is not current
2017-02-13 23:58:19,329 WARNING zuul.Scheduler: Build set <BuildSet item: <QueueItem 0x7f17f81c5310 for 142,396c6c21df72837189484f8232fda58588029b06 in gate_github> #builds: 0 merge state: PENDING> is not current
```

**Comment by gandelman-a** [comment] 2017-02-14 17:53
The following race can also trigger this, and easy to reproduce on a branch with both travis and bonny doing branch protection:

* Propose PR
* Human approves
* Travis starts
* Zuul check starts, finishes + passes
* Zuul gate starts, finishes + passes
* Travis still running
* Zuul tries to merge

**Comment by missaugustina** [comment] 2017-02-27 17:59
Looks like this was closed with the PR that merged.

**Closed as completed by missaugustina** 2017-02-27 17:59 UTC
Labels: bug
