### ISSUE TITLE
Community Engagement - Python Cryptography

### ISSUE THREAD

**Issue by pschwartz** [BonnyCI/projman#14] opened 2016-11-11 00:34 UTC

**Comment by missaugustina** [comment] 2016-12-07 01:46
Confirmed with dstufft, Python Cryptography is interested.

From dstufft: So Alex said he probably won't have much available time to help out much, but if cryptography can help they'd be more than willing to. Paul currently manages the Jenkins CI stuff that is running too so I suspect he'll be useful too. sounds like in general folks are open to trying to help out as their time permits. What might be best is for y'all to either poke #cryptography-dev about it, or maybe write up an email to the mailing list (https://mail.python.org/mailman/listinfo/cryptography-dev) as a sort of intro + sales pitch for what you'd like to do/setup/wahtever

**Comment by missaugustina** [comment] 2016-12-15 21:21
via cryptography-dev:

Hi Augustina,

cryptography's needs are a bit unusual. Since we depend on the underlying OS/distribution to provide us with OpenSSL (or commoncrypto on the macOS side) and we compile against a library that has a somewhat checkered past with versioning we have to test against numerous configurations. To achieve the coverage we want we currently use two different CI systems and aggregate coverage across them.

== Travis CI ==

Recent CI build: https://travis-ci.org/pyca/cryptography/builds/181337155

Travis CI gives us configuration-as-code, reasonable concurrency (we have 10 simultaneous builders, which is a godsend with the number of jobs we run), and support for both linux and macOS (multiple versions).

== Jenkins ==

Recent CI build: https://jenkins.cryptography.io/job/cryptography-master/1879/

Jenkins (using github pull request builder and multiconfiguration jobs) allows us to test unusual configs (like random test order) as well as against the set of configurations not supported by Travis. This includes Windows, FreeBSD, various linux distributions, and additional versions of macOS.

Jenkins also lets us build wheels for distribution during releases using the same infrastructure. We currently ship 21 wheels, but that number will grow shortly with Python 3.6.

Our current config is not using jenkinsfile (which has proven challenging to implement due to a variety of bugs) so the configs are not checked into CI and we commonly have to spend time working on the cluster since it's managed by us. However, an advantage this does offer is that our concurrency scales with our willingness to boot more VMs...


So, in an ideal world what we want out of CI is:

* Many OSes/distributions
* configuration as code
* high concurrency to minimize total CI time
* integration with github for status reporting
* fast and reliable booting of test instances (whether they're full VMs or containers)

As part of the "we want it to be fast" requirement being able to cache artifacts we may re-use repeatedly (like Python runtimes) can be extremely valuable in lowering total CI runtime.

If BonnyCI can offer this to us in the future then we'll be happy to take a close look!

-Paul Kehrer (reaperhulk)

**Comment by missaugustina** [comment] 2016-12-15 21:24
Next step:

- evaluate their current pipeline and come up with some quantitative metrics to better illustrate key points in the response
- collect the data identified ^^
- follow up with any clarifying questions

**Closed as completed** 2017-01-03 22:46 UTC
