### ISSUE TITLE
BonnyCI Service Outage - Nodepool was unable to login to DIB images

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#64] opened 2016-12-21 20:25 UTC
Issue Summary:

Timeline:
- how was the outage discovered?
- what steps were taken to restore service?
- what steps were taken to find root cause?
- when was service restored?

Root Cause Analysis:

Next Steps:

Further information:
https://review.openstack.org/#/c/413487/

**Comment by jamielennox** [comment] 2016-12-22 01:02
The root cause is interesting, but complex and from our perspective can be boiled down to DIB creating a bad image. The DIB image completed and was uploaded by nodepool but nodepool couldn't log in to it. 

This is bad nodepool behaviour. When nodepool couldn't boot an instance with this new image it would assume networking problems, take down the new node and try to rebuild another one - with the same bad image.

There are multiple things we should do here to catch/prevent this in future.

 - Nodepool shouldn't accept an image as good that it has never been able to ssh into. Currently if DIB succeeds and the image is uploaded nodepool will forever assume the image is good. Nodepool should have an additional validate step so that older known working images are not replaced until we get a successful usage of a new image.
- We should be able to detect this via monitoring.
  - If (ever?) nodepool cannot connect to a newly created virtual machine this is a problem and should raise an event we monitor. It either means bad networking or bad images and we care about both. 
  - We should monitor the number of available nodes on our CI and warn/alert when it drops below some number. 

The outage was discovered when github jobs we were watching never went to a completed state.
 - They did not get marked as failed, or no response they just never responded. This should be fixed, if a job does not complete with a given time it should notify us and the user.
 - We should monitor the time jobs take and notice a significant deviation. 
 - We should monitor the time it takes for a job to be assigned a node and notice a significant deviation. 

As this was an upstream DIB issue and we don't have production clients the issue was fixed upstream and released. This was helped by the fact that openstack-infra will have soon hit the same problem.
 - We don't have a way to apply local patches to dib. 
 - We don't have any way to functionally test an upgrade. 
 - DIB doesn't necessarily get updated when nodepool is updated. Hacky fix BonnyCI/hoist#20

Service restored 2016-12-22 01:00 UTC with release of DIB 1.26 and BonnyCI/hoist#20

**Comment by missaugustina** [comment] 2016-12-25 06:12
Before this issue can be closed, we need to create issues to track the additional work items mentioned. Thanks for the great write up Jamie!

**Comment by missaugustina** [comment] 2017-01-20 21:45
We still need to create tickets for the outstanding issues highlighted in this ticket.

**Comment by missaugustina** [comment] 2017-02-23 22:37
Help wanted: please review the information in this issue and create any new issues based on the information. Make sure any new issues aren't duplicates of anything that currently exists. Once that's done, or it's determined we don't need new issues, please update this ticket with the info and close it. be sure to reference this issue in any new issues you create based on it. Thx!

**Comment by loafyloaf** [comment] 2017-03-20 19:30
this is partly addressed in BonnyCI/projman#98

**Comment by loafyloaf** [comment] 2017-03-22 21:14
issues have been created from the info in this issue, and they all reference back to this one.

**Closed as completed by loafyloaf** 2017-03-22 21:14 UTC
Labels: help wanted, Service Outage
